{% set name = "python-rapidjson" %}
{% set version = "0.0.10" %}
{% set sha256 = "9927a9667b1fc6975a8af8a339a26416c69b1b5aa7705ce428e79a206892d3a0" %}
{% set rapidjson_version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  features:
    - vc10  # [win and py34]
    - vc14  # [win and py>34]
  skip: True  # [py27]

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - rapidjson =={{ rapidjson_version }}

  run:
    - python

test:
  imports:
    - rapidjson

about:
  home: https://github.com/python-rapidjson/python-rapidjson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python wrapper around rapidjson'
  description: |
    Python wrapper around RapidJSON. RapidJSON is an extremely fast C++ json serialization library.
    We do not support legacy python versions, you will need to upgrade to Python 3 to use this library.
  doc_url: https://python-rapidjson.readthedocs.io
  dev_url: https://github.com/python-rapidjson/python-rapidjson

extra:
  recipe-maintainers:
    - SylvainCorlay
    - hajapy
